name: show-environement
on: [push]
jobs:
  show-environement:
    runs-on: macos-latest
    steps:
      - name: Show production message
        if: ${{ secrets.ENVIRONMENT == 'Production' }}
        run: echo "I am running on Production"
      - name: Show Staging message
        if: ${{secretsenv.ENVIRONMENT == 'Staging' }}
        run: echo "I am running on Staging"
