name: show-environement
on: [push]
jobs:
  show-environement:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        # env:
        #   ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: "./.github/scripts/environment-demo.sh" ${{ secrets.ENVIRONMENT }}
#       - name: Show production message
#         if: ${{ env.ENVIRONMENT == "Production" }}
#         run: echo "I am running on Production"
#       - name: Show Staging message
#         if: ${{ env.ENVIRONMENT == "Staging" }}
#         run: echo "I am running on Staging"
