name: show-environement
on: [push]
jobs:
  show-environement:
    runs-on: macos-latest
    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}    
    steps:
      - name: Show production message
        if: ${{ $ENVIRONMENT == 'Production'}}
        run: echo "I am running on production"
      - name: Show Staging message
        if: ${{ $ENVIRONMENT == 'Staging' }}
        run: echo "I am running on Staging"
